### ISSUE TITLE
思考：能够做到按需加载css

### ISSUE THREAD

**Issue by veaba** [qq282126990/ivue-ui#1]
假如我们需要一个button，其他不需要，但我们还是要加载全部的css样式文件。

:+1:

**Comment by qq282126990** [comment]
其实是可以按需加载 css 的
如下： 
@import 'ivue-material/src/styles/custom.scss';
@import 'ivue-material/src/styles/mixins.scss';
@import 'ivue-material/src/styles/theme/index.scss';
@import 'ivue-material/src/styles/components/IVueButton.scss';
@import 'ivue-material/src/styles/components/IVueRipple.scss';

以上是 button 样式css

**Comment by veaba** [comment]
> 其实是可以按需加载 css 的
> 如下：
> @import 'ivue-material/src/styles/custom.scss';
> @import 'ivue-material/src/styles/mixins.scss';
> @import 'ivue-material/src/styles/theme/index.scss';
> @import 'ivue-material/src/styles/components/IVueButton.scss';
> @import 'ivue-material/src/styles/components/IVueRipple.scss';
> 以上是 button 样式css

也不太合乎场景，但需要引入大量的css，前提你得去看源码记下这个css路径。

如果我想用modal、button、tree，意味着可能又需要引入很多，除了自己的所属的，还需要引入其他公共的，动画、common。

- 更希望是 import {Button、Modal、tree} from "iVue"   即可。

但我记得，import cost的建议是，因为上面的引用会更大，下面小 

import Button from "iVue/Button"
import Modal from "iVue/Modal"
import Tree from "iVue/Tree"

至于上面的逻辑如何处理是需要考虑的问题

**Comment by qq282126990** [comment]
这种实现 需要每个组件都引入该组件的独立样式，但是这种实现不太现实，无法做到独立出css文件
